### PR TITLE
Prevented "should NOT see" from matching hidden text or text in script tags

### PR DESCRIPTION
**Pull request by mmcev106**
@aldefouw, let me know your thoughts on this one.  This change is also required to fix the "Perform REDCap upgrades" check in A.2.3.0300.

### CODE REVIEW

**Comment by aldefouw** [comment]
@mmcev106  - Clever idea to use index for cases where we do not want to match ... hmm, let me think about this - hopefully I have some time to review on Monday and get back to you.  I assume you made this modification to suit a specific problem we were having with this step definition incorrectly matching something that was hidden or invisible?

I think what's going to make these adjustments / modifications for step definitions easier for me to review in the long run is unit tests - so we should make that a priority as soon as we can.  Since we're having an ATS meeting this week, maybe we can also begin deploying ATS folks to help, too.

We're finally entering a phase of the project where I can have people focused on small elements of the code.

My other thought is we should leverage AI to help here.  I think we could have AI generate the unit test stubs for the step definitions so we have descriptions of what we're expecting.

I have a vision for a single static HTML page that contains all of the different types of elements we're looking for on one page and then use that HTML page as our reference source.  From there, we can test against the step definition and see whether our expectations are met?  A thought, anyway!

I'll resist the urge to fix this on a Saturday but it was worth thinking through at least.  Thanks again for looking at this, Mark.

**Comment by mmcev106** [comment]
@aldefouw, yes, I'm definitely in on prioritizing unit tests.  I just committed the change that depends on this PR to [this branch](https://github.com/4bbakers/redcap_rsvc/tree/perform-upgrades-fix).  That branch fails currently because the text is being matched in a script tag, even though it is not seen from the user's perspective.  If I was writing a unit tests for this, it would add assertions for the script tag case, and the case of elements that are present but hidden (both are mentioned in the comment on the PR).  That would of course be in addition to the basic assertions around whether the text exists at all or not.

**Comment by aldefouw** [comment]
This is looking good to me, @mmcev106 - looks like it passed the tests I would have expected to pass.  

I'll plan to approve and cut a new patch tag - v1.0.98.

**Comment by mmcev106** [comment]
Awesome!  Thank you.  Also, I don't get much credit for this solution. It was just the top stackoverflow answer for how to find text that is actually visible on the page (excluding hidden elements, script tags, etc.).

**Comment by aldefouw** [comment]
@mmcev106  - Should be available through v1.0.98 tag now.

**Pull request merged**
